#############################################################################
# Makefile for building: Labs3sem
# Generated by qmake (3.1) (Qt 6.6.0)
# Project:  Labs3sem.pro
# Template: app
# Command: C:\msys64\mingw64\bin\qmake6.exe -o Makefile Labs3sem.pro -spec win32-g++ "CONFIG+=qml_debug" "CONFIG+=qtquickcompiler" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\msys64\mingw64\bin\qmake6.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\msys64\mingw64\bin\qmake6.exe -install qinstall
QINSTALL_PROGRAM = C:\msys64\mingw64\bin\qmake6.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = widl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Labs3sem.pro ../../msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf ../../msys64/mingw64/share/qt6/mkspecs/features/spec_pre.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/device_config.prf \
		../../msys64/mingw64/share/qt6/mkspecs/common/sanitize.conf \
		../../msys64/mingw64/share/qt6/mkspecs/common/gcc-base.conf \
		../../msys64/mingw64/share/qt6/mkspecs/common/g++-base.conf \
		../../msys64/mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../msys64/mingw64/share/qt6/mkspecs/common/windows-vulkan.conf \
		../../msys64/mingw64/share/qt6/mkspecs/common/g++-win32.conf \
		../../msys64/mingw64/share/qt6/mkspecs/common/windows-desktop.conf \
		../../msys64/mingw64/share/qt6/mkspecs/qconfig.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3drender.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axserver.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_charts.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_grpc.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_location.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_location_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_nfc.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioning.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_repparser.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensors.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_websockets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webview.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri \
		../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		../../msys64/mingw64/share/qt6/mkspecs/features/qt_functions.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/qt_config.prf \
		../../msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf \
		../../msys64/mingw64/share/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/toolchain.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/default_pre.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/win32/default_pre.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/resolve_config.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/default_post.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/resolve_target.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/win32/separate_debug_info.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/resources_functions.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/qtquickcompiler.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/qml_debug.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/entrypoint.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/precompile_header.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/warn_on.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/permissions.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/qt.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/resources.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/moc.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/testlib_defines.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/win32/console.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/win32/opengl.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/uic.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/qmake_use.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/file_copies.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/testcase_targets.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/exceptions.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/yacc.prf \
		../../msys64/mingw64/share/qt6/mkspecs/features/lex.prf \
		Labs3sem.pro \
		../../msys64/mingw64/lib/Qt6EntryPoint.prl \
		../../msys64/mingw64/share/qt6/mkspecs/features/build_pass.prf \
		src_resources_qmlcache.qrc
	$(QMAKE) -o Makefile Labs3sem.pro -spec win32-g++ "CONFIG+=qml_debug" "CONFIG+=qtquickcompiler" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"
../../msys64/mingw64/share/qt6/mkspecs/features/spec_pre.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/device_config.prf:
../../msys64/mingw64/share/qt6/mkspecs/common/sanitize.conf:
../../msys64/mingw64/share/qt6/mkspecs/common/gcc-base.conf:
../../msys64/mingw64/share/qt6/mkspecs/common/g++-base.conf:
../../msys64/mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../msys64/mingw64/share/qt6/mkspecs/common/windows-vulkan.conf:
../../msys64/mingw64/share/qt6/mkspecs/common/g++-win32.conf:
../../msys64/mingw64/share/qt6/mkspecs/common/windows-desktop.conf:
../../msys64/mingw64/share/qt6/mkspecs/qconfig.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3drender.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axserver.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_charts.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_charts_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_grpc.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_location.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_location_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_nfc.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioning.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_repparser.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensors.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_websockets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webview.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webview_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri:
../../msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri:
../../msys64/mingw64/share/qt6/mkspecs/features/qt_functions.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/qt_config.prf:
../../msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf:
../../msys64/mingw64/share/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
../../msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/toolchain.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/default_pre.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/win32/default_pre.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/resolve_config.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/default_post.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/resolve_target.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/win32/separate_debug_info.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/resources_functions.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/qtquickcompiler.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/qml_debug.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/entrypoint.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/precompile_header.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/warn_on.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/permissions.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/qt.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/resources.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/moc.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/testlib_defines.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/win32/console.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/win32/opengl.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/uic.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/qmake_use.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/file_copies.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/testcase_targets.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/exceptions.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/yacc.prf:
../../msys64/mingw64/share/qt6/mkspecs/features/lex.prf:
Labs3sem.pro:
../../msys64/mingw64/lib/Qt6EntryPoint.prl:
../../msys64/mingw64/share/qt6/mkspecs/features/build_pass.prf:
src_resources_qmlcache.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Labs3sem.pro -spec win32-g++ "CONFIG+=qml_debug" "CONFIG+=qtquickcompiler" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\qtProjects\Labs3sem\Labs3sem.exe.debug .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
