// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_testquick();
Q_GHS_KEEP_REFERENCE(qml_register_types_testquick)

class testquickPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    testquickPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_testquick;
        Q_UNUSED(registration)
    }
};



#include "testquickplugin_testquickPlugin.moc"
